# Generated by Django 5.2.16 on 2026-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter your name', max_length=20)),
                ('address', models.CharField(help_text='enter your address', max_length=20)),
                ('price', models.PositiveBigIntegerField(help_text='enter your MRP: ')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
