# Generated by Django 5.2.16 on 2026-07-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='showproduct',
            table='product_list',
        ),
    ]
