# Generated by Django 5.2.16 on 2026-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0002_alter_showproduct_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproduct',
            name='price',
            field=models.PositiveBigIntegerField(help_text='enter  MRP of a device : '),
        ),
    ]
