# Generated by Django 5.2.16 on 2026-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0003_alter_showproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showproduct',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='showproduct',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='showproduct',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
