# Generated by Django 5.2.16 on 2026-07-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0004_alter_showproduct_address_alter_showproduct_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showproduct',
        ),
    ]
