# Generated by Django 5.2.16 on 2026-07-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_1', '0005_delete_showproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50, verbose_name='Subject Name')),
                ('school_open', models.TimeField()),
                ('school_close', models.TimeField()),
            ],
            options={
                'db_table': 'faculty_info',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='School Name')),
                ('address', models.CharField(max_length=100, verbose_name='School Address')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('school_mail', models.EmailField(max_length=100, verbose_name='School Email')),
            ],
            options={
                'db_table': 'schools_info',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='product_1.faculty', verbose_name='Subject')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faculties', to='product_1.school', verbose_name='School'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='product_1.grade', verbose_name='Grade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='product_1.school', verbose_name='School')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='product_1.student', verbose_name='Student')),
            ],
            options={
                'db_table': 'attendance_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Teacher Name')),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teachers', to='product_1.faculty', verbose_name='Faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teachers', to='product_1.school', verbose_name='School')),
            ],
            options={
                'db_table': 'teacher_info',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='product_1.teacher', verbose_name='Teacher'),
        ),
    ]
