# Generated by Django 5.2.16 on 2026-07-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_mail',
            field=models.EmailField(max_length=50, verbose_name='School Email'),
        ),
    ]
