# Generated by Django 5.2.16 on 2026-07-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0007_alter_school_contact_number_alter_school_school_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='contact_number',
            new_name='number',
        ),
    ]
