# Generated by Django 5.2.16 on 2026-07-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0008_rename_school_mail_school_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='number',
            new_name='snumber',
        ),
    ]
