# Generated by Django 5.2.16 on 2026-07-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0009_rename_mail_school_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='email',
            new_name='cl_mail',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='snumber',
            new_name='cl_number',
        ),
    ]
