# Generated by Django 5.2.16 on 2026-07-25 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_1', '0010_rename_email_school_cl_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Subject Code')),
                ('level', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11 (+2)'), ('12', 'Grade 12 (+2)'), ('bachelor', 'Bachelors'), ('master', 'Masters')], max_length=20, verbose_name='Level')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, verbose_name='Credit Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects_info',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['sub_name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11 (+2)'), ('12', 'Grade 12 (+2)'), ('bachelor', 'Bachelors'), ('master', 'Masters')], max_length=20, verbose_name='Grade'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('grade', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_f8b6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_738252_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_inf_name_5953a0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade'], name='student_inf_grade_i_e469b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'level')},
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='grades', to='product_1.subject', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='product_1.subject', verbose_name='Subjects'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='teacher_inf_name_4f8182_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school'], name='teacher_inf_school__390f41_idx'),
        ),
    ]
