# Generated by Django 5.2.16 on 2026-08-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('phone', models.PositiveBigIntegerField(unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('emergency_contact', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Emergency Contact')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
