# Generated by Django 6.1 on 2026-08-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Teacher ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('qualification', models.CharField(blank=True, choices=[('phd', 'PhD'), ('masters', "Master's Degree"), ('bachelors', "Bachelor's Degree"), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20, verbose_name='Qualification')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Specialization')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Years of Experience')),
                ('joining_date', models.DateField(auto_now_add=True, verbose_name='Joining Date')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
