# Generated by Django 5.2.16 on 2026-07-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter your name', max_length=30)),
                ('address', models.CharField(blank=True, help_text='Enter your address', max_length=10)),
                ('number', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'view_product',
            },
        ),
    ]
