# Generated by Django 5.2.13 on 2026-07-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(help_text='Enter your address', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveBigIntegerField(help_text='Enter your contact number', max_length=30, null=True),
        ),
    ]
