# Generated by Django 5.2.13 on 2026-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_address_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, help_text='Enter your contact number', null=True),
        ),
    ]
