# Generated by Django 5.2.13 on 2026-07-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='Unknown', help_text='Enter your address', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, help_text='Enter your product MRP.', null=True),
        ),
    ]
