# Generated by Django 6.1 on 2026-08-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('lab', 'Lab'), ('elective', 'Elective')], default='theory', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('class_name', models.CharField(max_length=20)),
                ('credit_hours', models.IntegerField(default=1)),
                ('full_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='Teacher.teacher')),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
    ]
