# Generated by Django 5.2.16 on 2026-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_school_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='school Name'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
