# Generated by Django 5.2.16 on 2026-08-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pharmacy_name')),
                ('registration_number', models.PositiveIntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.district', verbose_name='District')),
            ],
            options={
                'db_table': 'Pharmacy',
            },
        ),
    ]
