# Generated by Django 5.2.16 on 2026-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
    ]
