# Generated by Django 5.2.13 on 2026-07-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_is_active_alter_project_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
