# Generated by Django 5.2.16 on 2026-07-25 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, verbose_name='Faculty Name')),
                ('faculty_code', models.CharField(max_length=20, verbose_name='Faculty Code')),
                ('duration', models.PositiveSmallIntegerField(default=4, verbose_name='Duration (years)')),
                ('level', models.CharField(choices=[('school', 'School Level'), ('plus_two', '+2 / Intermediate'), ('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD')], default='bachelor', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_faculties',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, verbose_name='Grade Name')),
                ('grade_level', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11 (+2)'), ('12', 'Grade 12 (+2)'), ('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD')], max_length=20, verbose_name='Grade Level')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='Section')),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teacher Name')),
                ('total_students', models.PositiveSmallIntegerField(default=0, verbose_name='Total Students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_grades',
                'ordering': ['grade_level'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'project_students',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('subject_code', models.CharField(max_length=20, verbose_name='Subject Code')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semester')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, verbose_name='Credit Hours')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'project_subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='credit_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Credit Hours'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty',
            field=models.CharField(blank=True, choices=[('bbs', 'BBS (Bachelor of Business Studies)'), ('bca', 'BCA (Bachelor of Computer Application)'), ('bba', 'BBA (Bachelor of Business Administration)'), ('bit', 'BIT (Bachelor of Information Technology)'), ('csit', 'CSIT (Bachelor of Computer Science & IT)'), ('bed', 'B.Ed (Bachelor of Education)'), ('bcom', 'B.Com (Bachelor of Commerce)'), ('mca', 'MCA (Master of Computer Application)'), ('mit', 'MIT (Master of Information Technology)'), ('cseng', 'CS Eng (Computer Science Engineering)'), ('bsc_csit', 'BSc CSIT (Bachelor of Science in CSIT)'), ('bsc', 'BSc (Bachelor of Science)'), ('ba', 'BA (Bachelor of Arts)'), ('mbbs', 'MBBS (Bachelor of Medicine)'), ('mba', 'MBA (Master of Business Administration)'), ('msc', 'MSc (Master of Science)'), ('phd', 'PhD')], max_length=20, null=True, verbose_name='Faculty/Course'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Faculty Code'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_duration',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Duration (in years)'),
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_level',
            field=models.CharField(blank=True, choices=[('school', 'School Level'), ('plus_two', '+2 / Intermediate'), ('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD')], max_length=20, null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11 (+2)'), ('12', 'Grade 12 (+2)'), ('bachelor', 'Bachelors'), ('master', 'Masters'), ('phd', 'PhD')], max_length=20, null=True, verbose_name='Grade/Level'),
        ),
        migrations.AddField(
            model_name='project',
            name='grade_section',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Section (e.g., A, B, C)'),
        ),
        migrations.AddField(
            model_name='project',
            name='grade_teacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Teacher'),
        ),
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Enter your project full name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='Projects_name_52fb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['grade'], name='Projects_grade_d8a0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['faculty'], name='Projects_faculty_a33c41_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='Projects_is_acti_06a4d5_idx'),
        ),
        migrations.AddField(
            model_name='projectfaculty',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_faculties', to='home.project'),
        ),
        migrations.AddField(
            model_name='projectgrade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_grades', to='home.project'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='home.projectgrade'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_students', to='home.project'),
        ),
        migrations.AddField(
            model_name='projectsubject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='home.projectfaculty'),
        ),
        migrations.AddField(
            model_name='projectsubject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='home.projectgrade'),
        ),
        migrations.AddField(
            model_name='projectsubject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subjects', to='home.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfaculty',
            unique_together={('project', 'faculty_code')},
        ),
        migrations.AlterUniqueTogether(
            name='projectgrade',
            unique_together={('project', 'grade_name', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='projectsubject',
            unique_together={('project', 'subject_code')},
        ),
    ]
