# Generated by Django 5.2.16 on 2026-08-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Medicine Name')),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('medicine_code', models.IntegerField(unique=True)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('gel', 'Gel'), ('lotion', 'Lotion'), ('suspension', 'Suspension'), ('solution', 'Solution'), ('spray', 'Spray'), ('suppository', 'Suppository'), ('patch', 'Patch'), ('lozenge', 'Lozenge'), ('granules', 'Granules'), ('shampoo', 'Shampoo'), ('mouthwash', 'Mouthwash'), ('eye_drops', 'Eye Drops'), ('ear_drops', 'Ear Drops'), ('nasal_drops', 'Nasal Drops'), ('nasal_spray', 'Nasal Spray'), ('iv_fluid', 'IV Fluid')], default='tablet', max_length=20)),
                ('strength', models.CharField(help_text='store mg/mcg/IU/mL of medicine', max_length=10)),
                ('barcode', models.PositiveIntegerField(unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.IntegerField(default=10)),
                ('storage_location', models.CharField(blank=True, max_length=150, null=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('expired', 'Expired')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
