# Generated by Django 5.2.16 on 2026-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_category_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Catgeory Name'),
        ),
    ]
