# Generated by Django 5.2.16 on 2026-08-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
