# Generated by Django 5.2.16 on 2026-08-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_medicine_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.category'),
        ),
    ]
