# Generated by Django 5.2.16 on 2026-08-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_category_medicine_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Category',
            new_name='category',
        ),
    ]
