# Generated by Django 5.2.16 on 2026-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_rename_category_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='Requires Prescription'),
        ),
    ]
