# Generated by Django 5.2.16 on 2026-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_category_out_of_stock_category_requires_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='requires_prescription',
            field=models.BooleanField(default=True, verbose_name='Requires Prescription'),
        ),
    ]
