# Generated by Django 5.2.16 on 2026-08-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_category_requires_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='requires_prescription',
            field=models.TextField(default=True, verbose_name='Requires Prescription'),
        ),
    ]
