# Generated by Django 6.1 on 2026-08-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
