# Generated by Django 5.2.16 on 2026-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('address', models.CharField(help_text='Enter your current location', max_length=200)),
                ('course', models.CharField(help_text='Course name to enroll', max_length=100)),
                ('contact', models.PositiveBigIntegerField(help_text='Enter your contact number', max_length=20)),
            ],
            options={
                'db_table': 'students_info',
            },
        ),
    ]
