# Generated by Django 5.2.16 on 2026-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='contact',
        ),
        migrations.AlterField(
            model_name='datastore',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
