# Generated by Django 5.2.16 on 2026-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_remove_datastore_contact_alter_datastore_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
