# Generated by Django 5.2.16 on 2026-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_datastore_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='email',
            field=models.EmailField(default='example12@gmail.com', max_length=254),
        ),
    ]
