# Generated by Django 5.2.16 on 2026-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_datastore_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='number',
            field=models.PositiveBigIntegerField(default='9700000000'),
        ),
    ]
