# Generated by Django 5.2.16 on 2026-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_datastore_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='email',
            field=models.EmailField(help_text='example12@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='number',
            field=models.PositiveBigIntegerField(help_text='9700000000'),
        ),
    ]
